"""API-specific configuration, reusing pipeline constants."""

import sys
from pathlib import Path

# Ensure pipeline is importable
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pipeline.config import (
    BUCKET_LABELS,
    TIER_LABELS,
    TIER_COLORS,
    SCORE_BUCKET_THRESHOLDS,
    FEATURE_DISPLAY_NAMES,
    WORKING_PKLS,
    CONFIG_LABELS,
    CONFIG_SHORT,
    ID_COLUMN,
    TARGET_SCORE,
    TARGET_BUCKET,
    BUCKET_MAP,
    NUMERIC_FEATURES,
    BINARY_FEATURES,
    STRUCTURED_FEATURES,
    ENGINEERED_FEATURES,
    EXPERIENCE_BINARY_FLAGS,
    ALL_RUBRIC_DIMS,
    PS_DIMS,
    EXPERIENCE_QUALITY_DIMS,
    SECONDARY_DIMS,
    PROTECTED_ATTRIBUTES,
    DEMOGRAPHICS_FOR_FAIRNESS_ONLY,
    PROCESSED_DIR,
    MODELS_DIR,
    CACHE_DIR,
    prettify,
    score_to_tier,
)

# Re-export everything for API routers
__all__ = [
    "BUCKET_LABELS", "TIER_LABELS", "TIER_COLORS", "SCORE_BUCKET_THRESHOLDS",
    "FEATURE_DISPLAY_NAMES", "WORKING_PKLS", "CONFIG_LABELS", "CONFIG_SHORT",
    "ID_COLUMN", "TARGET_SCORE", "TARGET_BUCKET", "BUCKET_MAP",
    "NUMERIC_FEATURES", "BINARY_FEATURES", "STRUCTURED_FEATURES",
    "ENGINEERED_FEATURES", "EXPERIENCE_BINARY_FLAGS",
    "ALL_RUBRIC_DIMS", "PS_DIMS", "EXPERIENCE_QUALITY_DIMS", "SECONDARY_DIMS",
    "PROTECTED_ATTRIBUTES", "DEMOGRAPHICS_FOR_FAIRNESS_ONLY",
    "PROCESSED_DIR", "MODELS_DIR", "CACHE_DIR",
    "prettify", "score_to_tier", "PROJECT_ROOT",
]
